version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./mnt/data/products:/data:ro
      - ./templates:/templates:ro
    ports:
      - "32933:80"
    depends_on:
      - "ui"
      # - "api"
    environment:
      TZ: America/Denver
  ui:
    image: node:21
    working_dir: /app/ui
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./ui:/app/ui
    environment:
      TZ: America/Denver
  api:
    image: bobbins-api:latest
    build:
      context: api
    working_dir: /app/api
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: uvicorn main:fastapi_app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/api
      - ./mnt/data:/data
      - ./templates:/app/templates:ro
      - ./mnt/logs:/var/log/bobbins/api
    environment:
      TZ: America/Denver
